# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Fit Autofluorescence Joint — C++ implementation
#'
#' @description
#' C++ equivalent of \code{fit.af.joint()}. Selects the best-fitting
#' autofluorescence spectrum per cell using a combined proportional score that
#' balances two complementary error signals:
#'
#' \itemize{
#'   \item \strong{Fluorophore spillover} (\code{p_fluor}): L1 norm of unmixed
#'     fluorophore values after subtracting the AF shadow, expressed as a
#'     proportion of the baseline spillover with no AF correction at all.
#'   \item \strong{Raw-space residual} (\code{p_resid}): L2 norm of the
#'     detector-space residual after subtracting the fitted AF signal,
#'     expressed as a proportion of the baseline residual with no AF
#'     correction.
#' }
#'
#' The combined score for variant \eqn{j} is
#' \deqn{\text{score}_j = \alpha \cdot p_{\text{resid},j}
#'       + (1-\alpha) \cdot p_{\text{fluor},j}}
#' and the variant that minimises this score is selected.
#'
#' The unmixing matrix \eqn{P = (SS^T)^{-1}S} is computed internally from
#' \code{spectra}. Any \code{"AF"} row in \code{spectra} is silently stripped
#' before use, matching the behaviour of the R implementation.
#'
#' @param raw_data       Numeric matrix, cells × detectors.
#' @param unmixed        Numeric matrix, cells × fluorophores. OLS unmixed
#'   values computed without any AF correction (fluorophore spectra only).
#' @param spectra        Numeric matrix, fluorophores × detectors. Row names
#'   must be set; any row named \code{"AF"} is dropped automatically.
#' @param af_spectra     Numeric matrix, AF variants × detectors.
#' @param alpha          Numeric scalar in `[0, 1]` (default 0.5). Weight for
#'   the raw-detector residual term relative to the fluorophore-spillover
#'   term.
#' @param n_threads      Integer. Number of OpenMP threads (default 1).
#'
#' @return A named \code{List} with four elements:
#' \describe{
#'   \item{\code{unmixed}}{Matrix (cells × fluorophores) of AF-corrected
#'     unmixed values.}
#'   \item{\code{AF}}{Numeric vector (length \code{nrow(raw_data)}) of
#'     per-cell AF intensities (the fitted scalar \eqn{k}).}
#'   \item{\code{af.idx}}{Integer vector of the AF variant index selected per
#'     cell (1-based).}
#'   \item{\code{fitted.af}}{Matrix (cells × detectors) of the AF signal
#'     projected back into raw detector space.}
#' }
#'
#' @export
fit_af_joint_cpp <- function(raw_data, unmixed, spectra, af_spectra, alpha = 0.5, n_threads = 1L) {
    .Call(`_FlowCodeUnmixRcpp_fit_af_joint_cpp`, raw_data, unmixed, spectra, af_spectra, alpha, n_threads)
}

#' @title Fit FRET Signals Joint — C++ implementation
#'
#' @description
#' C++ equivalent of \code{fit.fret.joint()}.  Selects the best-fitting FRET
#' correction spectrum per cell using a combined proportional score that
#' balances two complementary error signals:
#'
#' \itemize{
#'   \item \strong{Off-channel fluorophore spillover} (\code{p_fluor}): L1 norm
#'     of unmixed values in the fluorophores that are \emph{absent} from the
#'     cell's FlowCode barcode (the "OFF channels"), after subtracting the FRET
#'     shadow.  Expressed as a proportion of the baseline OFF-channel spillover
#'     with no FRET correction.
#'   \item \strong{Raw-space residual} (\code{p_resid}): L2 norm of the
#'     detector-space residual after subtracting the fitted FRET signal,
#'     expressed as a proportion of the baseline residual with no FRET
#'     correction.
#' }
#'
#' The combined score for variant \eqn{j} is
#' \deqn{\text{score}_j = \alpha \cdot p_{\text{resid},j}
#'       + (1-\alpha) \cdot p_{\text{fluor},j}}
#' and the variant that minimises this score is selected.
#'
#' Because FRET spectra differ per barcode, the function receives a
#' \code{List} of per-barcode FRET matrices and an integer vector
#' (\code{cell_barcode_ids}) that maps each cell to its barcode.  The OLS
#' unmixing matrix \eqn{P = (SS^T)^{-1}S} is computed once internally from
#' \code{spectra}.  Cells that belong to a placeholder barcode (a single
#' all-zero FRET row) are returned uncorrected.
#'
#' @param raw_data         Numeric matrix, cells × detectors.
#' @param unmixed          Numeric matrix, cells × fluorophores.  OLS unmixed
#'   values computed without any FRET correction.
#' @param spectra          Numeric matrix, fluorophores × detectors.
#' @param fret_spectra_list A \code{List} of numeric matrices, one per
#'   barcode ID.  Each matrix is FRET-variants × detectors.  The list is
#'   1-indexed; element \code{i} corresponds to barcode ID \code{i}.
#' @param cell_barcode_ids Integer vector (length \code{nrow(raw_data)}).
#'   Barcode ID for each cell (1-based, matching \code{fret_spectra_list}).
#' @param off_indices_list A \code{List} of integer vectors (one per barcode
#'   ID), each giving the 1-based column indices into \code{unmixed} that are
#'   the OFF-channel fluorophores for that barcode.
#' @param alpha            Numeric scalar in `[0, 1]` (default 0.5).  Weight for
#'   the raw-detector residual term relative to the off-channel fluorophore
#'   spillover term.
#' @param n_threads        Integer.  Number of OpenMP threads (default 1).
#'
#' @return A named \code{List} with two elements:
#' \describe{
#'   \item{\code{unmixed}}{Matrix (cells × fluorophores) of FRET-corrected
#'     unmixed values.}
#'   \item{\code{fitted.fret}}{Matrix (cells × detectors) of the FRET signal
#'     projected back into raw detector space.}
#' }
#'
#' @export
fit_fret_joint_cpp <- function(raw_data, unmixed, spectra, fret_spectra_list, cell_barcode_ids, off_indices_list, alpha = 0.5, n_threads = 1L) {
    .Call(`_FlowCodeUnmixRcpp_fit_fret_joint_cpp`, raw_data, unmixed, spectra, fret_spectra_list, cell_barcode_ids, off_indices_list, alpha, n_threads)
}

unmix_flowcode_pipeline_cpp <- function(raw_data_in, spectra, af_spectra, fluor_names, flowcode_fluors, flowcode_tags, flowcode_thresholds, valid_combos, flowcode_logical, fret_spectra_list, pos_thresholds, optimize_fluors, variants, delta_list, delta_norms, k_opt = 1L, n_threads = 1L, optimize = TRUE) {
    .Call(`_FlowCodeUnmixRcpp_unmix_flowcode_pipeline_cpp`, raw_data_in, spectra, af_spectra, fluor_names, flowcode_fluors, flowcode_tags, flowcode_thresholds, valid_combos, flowcode_logical, fret_spectra_list, pos_thresholds, optimize_fluors, variants, delta_list, delta_norms, k_opt, n_threads, optimize)
}

