# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

optimize_flowcode_unmix <- function(raw_data, unmixed, combined_spectra, weights, pos_thresholds, af_idx, af_spectra, flowcode_ids, has_flowcode, combo_fret, fret_delta_list, fret_delta_norms, flowcode_combo_logical, flowcode_fluors, optimize_fluors, variants, delta_list, delta_norms, all_fluor_names, af_idx_in_spectra, k = 10L, weighted = FALSE, cell_weighting = FALSE, cell_weight_regularize = FALSE, nthreads = 1L) {
    .Call(`_FlowCodeUnmixRcpp_optimize_flowcode_unmix`, raw_data, unmixed, combined_spectra, weights, pos_thresholds, af_idx, af_spectra, flowcode_ids, has_flowcode, combo_fret, fret_delta_list, fret_delta_norms, flowcode_combo_logical, flowcode_fluors, optimize_fluors, variants, delta_list, delta_norms, all_fluor_names, af_idx_in_spectra, k, weighted, cell_weighting, cell_weight_regularize, nthreads)
}

