# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

unmix_flowcode_pipeline_cpp <- function(raw_data, spectra, af_spectra, fluor_names, flowcode_fluors, flowcode_tags, flowcode_thresholds, valid_combos, flowcode_logical, fret_spectra_list, pos_thresholds, optimize_fluors, variants, delta_list, delta_norms, k_opt = 1L, n_threads = 1L, optimize = TRUE) {
    .Call(`_FlowCodeUnmixRcpp_unmix_flowcode_pipeline_cpp`, raw_data, spectra, af_spectra, fluor_names, flowcode_fluors, flowcode_tags, flowcode_thresholds, valid_combos, flowcode_logical, fret_spectra_list, pos_thresholds, optimize_fluors, variants, delta_list, delta_norms, k_opt, n_threads, optimize)
}

